  main = ".open-next/worker.js"
  name = "evaly"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat_v2"]

  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  [observability.logs]
  enabled = true