name: Deploy SST Application

on:
  push:
    branches:
      - main
      - staging
      - development
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Determine deployment stage
        id: set-stage
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "STAGE=${{ github.event.inputs.stage }}" >> $GITHUB_ENV
          else
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "STAGE=production" >> $GITHUB_ENV
            elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
              echo "STAGE=staging" >> $GITHUB_ENV
            else
              echo "STAGE=development" >> $GITHUB_ENV
            fi
          fi

