/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as participantRouteImport } from './routes/(participant)/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppSettingsImport } from './routes/app/settings'
import { Route as AppParticipantsImport } from './routes/app/participants'
import { Route as AppTestsIndexImport } from './routes/app/tests/index'
import { Route as AppQuestionsIndexImport } from './routes/app/questions/index'
import { Route as AppTestsDetailsImport } from './routes/app/tests/details'
import { Route as AppQuestionsDetailsImport } from './routes/app/questions/details'
import { Route as participantSTestIdIndexImport } from './routes/(participant)/s.$testId.index'
import { Route as participantSTestIdAttemptIdImport } from './routes/(participant)/s.$testId.$attemptId'

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const participantRouteRoute = participantRouteImport.update({
  id: '/(participant)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppParticipantsRoute = AppParticipantsImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTestsIndexRoute = AppTestsIndexImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppQuestionsIndexRoute = AppQuestionsIndexImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTestsDetailsRoute = AppTestsDetailsImport.update({
  id: '/tests/details',
  path: '/tests/details',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppQuestionsDetailsRoute = AppQuestionsDetailsImport.update({
  id: '/questions/details',
  path: '/questions/details',
  getParentRoute: () => AppRouteRoute,
} as any)

const participantSTestIdIndexRoute = participantSTestIdIndexImport.update({
  id: '/s/$testId/',
  path: '/s/$testId/',
  getParentRoute: () => participantRouteRoute,
} as any)

const participantSTestIdAttemptIdRoute =
  participantSTestIdAttemptIdImport.update({
    id: '/s/$testId/$attemptId',
    path: '/s/$testId/$attemptId',
    getParentRoute: () => participantRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(participant)': {
      id: '/(participant)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof participantRouteImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/app/participants': {
      id: '/app/participants'
      path: '/participants'
      fullPath: '/app/participants'
      preLoaderRoute: typeof AppParticipantsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/questions/details': {
      id: '/app/questions/details'
      path: '/questions/details'
      fullPath: '/app/questions/details'
      preLoaderRoute: typeof AppQuestionsDetailsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/tests/details': {
      id: '/app/tests/details'
      path: '/tests/details'
      fullPath: '/app/tests/details'
      preLoaderRoute: typeof AppTestsDetailsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/questions/': {
      id: '/app/questions/'
      path: '/questions'
      fullPath: '/app/questions'
      preLoaderRoute: typeof AppQuestionsIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/tests/': {
      id: '/app/tests/'
      path: '/tests'
      fullPath: '/app/tests'
      preLoaderRoute: typeof AppTestsIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/(participant)/s/$testId/$attemptId': {
      id: '/(participant)/s/$testId/$attemptId'
      path: '/s/$testId/$attemptId'
      fullPath: '/s/$testId/$attemptId'
      preLoaderRoute: typeof participantSTestIdAttemptIdImport
      parentRoute: typeof participantRouteImport
    }
    '/(participant)/s/$testId/': {
      id: '/(participant)/s/$testId/'
      path: '/s/$testId'
      fullPath: '/s/$testId'
      preLoaderRoute: typeof participantSTestIdIndexImport
      parentRoute: typeof participantRouteImport
    }
  }
}

// Create and export the route tree

interface participantRouteRouteChildren {
  participantSTestIdAttemptIdRoute: typeof participantSTestIdAttemptIdRoute
  participantSTestIdIndexRoute: typeof participantSTestIdIndexRoute
}

const participantRouteRouteChildren: participantRouteRouteChildren = {
  participantSTestIdAttemptIdRoute: participantSTestIdAttemptIdRoute,
  participantSTestIdIndexRoute: participantSTestIdIndexRoute,
}

const participantRouteRouteWithChildren =
  participantRouteRoute._addFileChildren(participantRouteRouteChildren)

interface AppRouteRouteChildren {
  AppParticipantsRoute: typeof AppParticipantsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppQuestionsDetailsRoute: typeof AppQuestionsDetailsRoute
  AppTestsDetailsRoute: typeof AppTestsDetailsRoute
  AppQuestionsIndexRoute: typeof AppQuestionsIndexRoute
  AppTestsIndexRoute: typeof AppTestsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppParticipantsRoute: AppParticipantsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppQuestionsDetailsRoute: AppQuestionsDetailsRoute,
  AppTestsDetailsRoute: AppTestsDetailsRoute,
  AppQuestionsIndexRoute: AppQuestionsIndexRoute,
  AppTestsIndexRoute: AppTestsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof participantRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/participants': typeof AppParticipantsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/questions/details': typeof AppQuestionsDetailsRoute
  '/app/tests/details': typeof AppTestsDetailsRoute
  '/app/questions': typeof AppQuestionsIndexRoute
  '/app/tests': typeof AppTestsIndexRoute
  '/s/$testId/$attemptId': typeof participantSTestIdAttemptIdRoute
  '/s/$testId': typeof participantSTestIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof participantRouteRouteWithChildren
  '/app/participants': typeof AppParticipantsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/questions/details': typeof AppQuestionsDetailsRoute
  '/app/tests/details': typeof AppTestsDetailsRoute
  '/app/questions': typeof AppQuestionsIndexRoute
  '/app/tests': typeof AppTestsIndexRoute
  '/s/$testId/$attemptId': typeof participantSTestIdAttemptIdRoute
  '/s/$testId': typeof participantSTestIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(participant)': typeof participantRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/participants': typeof AppParticipantsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/questions/details': typeof AppQuestionsDetailsRoute
  '/app/tests/details': typeof AppTestsDetailsRoute
  '/app/questions/': typeof AppQuestionsIndexRoute
  '/app/tests/': typeof AppTestsIndexRoute
  '/(participant)/s/$testId/$attemptId': typeof participantSTestIdAttemptIdRoute
  '/(participant)/s/$testId/': typeof participantSTestIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/participants'
    | '/app/settings'
    | '/app/'
    | '/app/questions/details'
    | '/app/tests/details'
    | '/app/questions'
    | '/app/tests'
    | '/s/$testId/$attemptId'
    | '/s/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/participants'
    | '/app/settings'
    | '/app'
    | '/app/questions/details'
    | '/app/tests/details'
    | '/app/questions'
    | '/app/tests'
    | '/s/$testId/$attemptId'
    | '/s/$testId'
  id:
    | '__root__'
    | '/'
    | '/(participant)'
    | '/app'
    | '/app/participants'
    | '/app/settings'
    | '/app/'
    | '/app/questions/details'
    | '/app/tests/details'
    | '/app/questions/'
    | '/app/tests/'
    | '/(participant)/s/$testId/$attemptId'
    | '/(participant)/s/$testId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  participantRouteRoute: typeof participantRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  participantRouteRoute: participantRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(participant)",
        "/app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(participant)": {
      "filePath": "(participant)/route.tsx",
      "children": [
        "/(participant)/s/$testId/$attemptId",
        "/(participant)/s/$testId/"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/participants",
        "/app/settings",
        "/app/",
        "/app/questions/details",
        "/app/tests/details",
        "/app/questions/",
        "/app/tests/"
      ]
    },
    "/app/participants": {
      "filePath": "app/participants.tsx",
      "parent": "/app"
    },
    "/app/settings": {
      "filePath": "app/settings.tsx",
      "parent": "/app"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/questions/details": {
      "filePath": "app/questions/details.tsx",
      "parent": "/app"
    },
    "/app/tests/details": {
      "filePath": "app/tests/details.tsx",
      "parent": "/app"
    },
    "/app/questions/": {
      "filePath": "app/questions/index.tsx",
      "parent": "/app"
    },
    "/app/tests/": {
      "filePath": "app/tests/index.tsx",
      "parent": "/app"
    },
    "/(participant)/s/$testId/$attemptId": {
      "filePath": "(participant)/s.$testId.$attemptId.tsx",
      "parent": "/(participant)"
    },
    "/(participant)/s/$testId/": {
      "filePath": "(participant)/s.$testId.index.tsx",
      "parent": "/(participant)"
    }
  }
}
ROUTE_MANIFEST_END */
